---
title: "Data Transformation"
author: "Ray Hunter"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
```







```{r}
flights
filter(flights, arr_delay <= 120, dep_delay <= 120)


#If you want to determine if a value is missing, use is.na()
```

##### filter

```{r}
# Find all flights that

# Had an arrival delay of two or more hours
filter(flights, arr_delay >= 2)

# Flew to Houston (IAH or HOU)

filter(flights, dest == c("IAH", "HOU"))

# Were operated by United, American, or Delta
filter(flights, dest == c("UA", "DL", "AA"))

# Departed in summer (July, August, and September)


# Arrived more than two hours late, but didn’t leave late

filter(flights, arr_delay > 2, dep_delay == 0)


# Were delayed by at least an hour, but made up over 30 minutes in flight
# Departed between midnight and 6am (inclusive)

filter(flights, between(dep_time, 600, 1200))
# Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
# 
# How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
filter(flights, is.na(flights$dep_time))

# Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)


```



### arrange function 



```{r}
#arrange function changes the order of the rows depending on what is being called 
 arrange(flights, year, month, day)

#desc() makes therows descend based off that vector 
arrange(flights, desc(dep_delay))




# How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).

arrange(flights, desc(is.na(flights)) )
# 

# Sort flights to find the most delayed flights. Find the flights that left earliest.
arrange(flights, desc(dep_delay))
# Sort flights to find the fastest (highest speed) flights.
arrange(flights, arr_delay)
# Which flights travelled the farthest? Which travelled the shortest?
arrange(flights, air_time)
arrange(flights, desc(air_time))


```



#####select function

```{r}
select(flights, year, month, day)
select(flights, year:day)
select(flights, -(year:day))

#ex:
select(flights, starts_with("arr"))
select(flights, contains("arr"))
select(flights, matches("time"))


# There are a number of helper functions you can use within select():
# 
# starts_with("abc"): matches names that begin with “abc”.
# 
# ends_with("xyz"): matches names that end with “xyz”.
# 
# contains("ijk"): matches names that contain “ijk”.
# 
# matches("(.)\\1"): selects variables that match a regular expression. This one matches any variables that contain repeated characters. You’ll learn more about regular expressions in strings.
# 
# num_range("x", 1:3): matches x1, x2 and x3.
```



### rename
```{r}
rename(flights, tail_num = tailnum)
```


```{r}
# Another option is to use select() in conjunction with the everything() helper. This is useful if you have a handful of variables you’d like to move to the start of the data frame.

select(flights, time_hour, air_time, everything())

vars <- c("year", "month", "day", "dep_delay", "arr_delay", "weiner")
select(flights, any_of(vars))

#compared to 
select(flights, any_of(vars))

#this doesnt work b/c weiner is not a vector in this data set 



select(flights, contains("TIME"))
select(flights, matches("TIME"))
```




##### mutate 


```{r}
flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml,
  gain = dep_delay - arr_delay,
  speed = distance / air_time * 60)



#only keep the new variables 
transmute(flights,
  gain = dep_delay - arr_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours)


#extracting the hour and the minute from a a set of numbers
transmute(flights,
  dep_time,
  #integer division 
  hour = dep_time %/% 100,
  #remainder devision
  minute = dep_time %% 100
)
```


lead and lag 



```{r}
# Offsets: lead() and lag() allow you to refer to leading or lagging values. This allows you to compute running differences (e.g. x - lag(x)) or find when values change (x != lag(x)). They are most useful in conjunction with group_by(), which you’ll learn about shortly.

(x <- 1:10)
#>  [1]  1  2  3  4  5  6  7  8  9 10
lag(x)
#>  [1] NA  1  2  3  4  5  6  7  8  9
lead(x)
#>  [1]  2  3  4  5  6  7  8  9 10 NA
```





## cummulative and rolling aggregates

```{r}

# Cumulative and rolling aggregates: R provides functions for running sums, products, mins and maxes: cumsum(), cumprod(), cummin(), cummax(); and dplyr provides cummean() for cumulative means. If you need rolling aggregates (i.e. a sum computed over a rolling window), try the RcppRoll package.

x
#>  [1]  1  2  3  4  5  6  7  8  9 10
cumsum(x)
#>  [1]  1  3  6 10 15 21 28 36 45 55
cummean(x)
#>  [1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5
```



```{r}
# Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.



#converting the combined hour an dminutes to minutes 
mutate(flights, dep_minutes = (dep_time %/% 100*60) + (dep_time %% 100)  )

# 
# Compare air_time with arr_time - dep_time. What do you expect to see? What do you see? What do you need to do to fix it?

mutate(flights, time_in_air = (arr_time%/% 100*60 + arr_time%% 100) - (dep_time%/% 100*60 + dep_time%% 100))  %>% 
  select( air_time, time_in_air) 






# Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
# 
# Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for min_rank().

mutate(flights, rank = min_rank(desc(dep_delay))) %>% 
arrange(rank)



# What does 1:3 + 1:10 return? Why?
# 
# What trigonometric functions does R provide?
```



##### group by with summarise 

```{r}
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))
```

























































